### ISSUE TITLE
Graphs not showing on tutorial tabs when running on local

### ISSUE THREAD

**Issue by vrios** [lageIBUSP/Rsampling-shiny#41]
Seen on Windows 8 and Windows XP
Sometimes when loading, graphs do not appear on tutorial tabs, and an error message is shown on console:
![error](https://cloud.githubusercontent.com/assets/6096816/9071890/3eec99dc-3ace-11e5-956f-7f322d8f8561.jpg)

Error appears ramdomly on some Windows 8 systems, but constanly on windows XP

**Comment by andrechalom** [comment]
Any reports of this bug on Linux? I am currently unable to test this under
Windows, so I can't help with this issue.

**Comment by ayanamartins** [comment]
@andrechalom , I just experienced this same bug on Linux. 
I re-ran the app without changing anything and it worked just fine (?)

**Comment by andrechalom** [comment]
I'm still unable to reproduce, let alone understand this bug. Can you give more details? Maybe the bug is related to the R version? Or to the shiny library version? Do all graphs disapear or just the histograms? Do the graph on the Resampling tab still work? As the message is about "hist.default", it seems that the problem should be on the histogram, but I don't understand how it can make the graphs disappear.

The "no matches for text" is certainly unrelated, fixed it on master now.

**Comment by ayanamartins** [comment]
I just ran into this bug once more.

It seems that it causes the program to stop altogether. All graphs disappear and all tabs stop working. It is not possible to load a data set on the input tab after the bug takes place. Therefore, nothing else works.

I tried to set the random seed to see if I could repeat the error, however I guess I don't know how to do that for a shiny app. Placing the set.seed function on server.R doesn't seem to work...

**Comment by andrechalom** [comment]
Running tests on Windows 8 64 bits; R 3.3.0 installed with x86 and x64, running on x64, clean installation, with shiny 0.13.2

I've run the installation following the instructions on README, without any error. I have also downloaded the source instead of running from web, as there are reports that this might be a problem.

The interface opens fine in Firefox 46.0.1. I have repeated the process of opening the interface on the tutorial tab and running a couple of iterations of the randomizations 20 times to make sure that this bug is not caused by a random seed - or that if it is, at least it's rare enough.

Then I have changed to Chrome 50.0.2661.102 and repeated the same iterations. No problems again.

If someone is encountering this problem, I strongly suggest upgrading your system. Official support for Windows XP ended on April 8, 2014.
