### ISSUE TITLE
Mean difference of columns statistics

### ISSUE THREAD

**Issue by adalardo** [lageIBUSP/Rsampling-shiny#52]
The "protective ants" tutorial shows the "mean difference" statistic for a dependent data (same plant). All looks right. I tried to redo the tutorial using azteca input data and selecting the "mean difference  between columns" and within rows randomization. The data looks the same but the statistic of interest is not the same. Something looks wrong!  Or another plausible hypothesis but with a very low probability:  I doing something wrong!

**Comment by ayanamartins** [comment]
I could not reproduce this error, or perhaps I didn't understand what the problem is.  I tried:
**Data input tab**
What is your input data? azteca
**Statistics tab**
Statistic: mean difference between columns 
Before treatment: extract.old
After treatment: extract.new
Statistic of interest = 7.333 (which is the same as in the tutorial)
**Resampling tab**
The statistic of interest is not written there (right?), however the red dashed line appeared to be in the right place (between 7 and 7.5)

**Comment by andrechalom** [comment]
@adalardo, I was also unable to reproduce the issue you have reported. The azteca tutorial (after some resampling) looks like this:

![ale1](https://cloud.githubusercontent.com/assets/1994997/15660220/7ca37bf6-26af-11e6-98a1-58ce60d262c5.png)

As you can see, the statistic of interest is 7.3333 (mean difference), and the p value of the resampling is very low.

Reproducing the data from the tutorial, as @ayanamartins did, I have found the same statistic of interest (mean difference = 7.33333), and this resampling graph:

![ale2](https://cloud.githubusercontent.com/assets/1994997/15660242/e2f815e2-26af-11e6-8257-d6509ab21df6.png)

With this, I am inclined to agree with the famous detective Sherlock Holmes, who once said that "when you have eliminated the impossible, whatever remains, _however improbable_, must be the truth".

If you have any other input, please comment and we will re-open the issue.
